### ISSUE TITLE
此时不应有 \MiPhoneAssistant”文件夹，或直接安装在手机后，按任意键重试。

### ISSUE THREAD

**Issue by a76854** [gucong3000/MiuiCleaner#1]
做了上述步骤，将cmd文件移动至C:\Program Files (x86)\MiPhoneAssistant
显示”此时不应有 \MiPhoneAssistant”文件夹，或直接安装在手机后，按任意键重试。”

**Comment by gucong3000** [comment]
已得到修复，可以下载 [MiuiCleaner.cmd](https://github.com/gucong3000/MiuiCleaner/releases/download/v2022.9.21.4/MiuiCleaner.cmd) 试试
