### ISSUE TITLE
没有自动提示打开无障碍，运行卸载程序也未生效

### ISSUE THREAD

**Issue by tangjyan** [gucong3000/MiuiCleaner#4]
![Screenshot_2022-09-29-22-52-14-809-edit_com githu](https://user-images.githubusercontent.com/21167731/193065433-e00816f3-274a-477a-94b1-6dfda91b2b37.jpg)

**Comment by gucong3000** [comment]
首先，请更新一下版本：https://github.com/gucong3000/MiuiCleaner/releases

其次，如果依然出现同样问题，请杀掉MiuiCleaner，再次打开即可恢复正常。
可以在MIUI的最近任务管理界面滑掉，也可以在应用信息页面点“结束运行”。
