### ISSUE TITLE
应用启动后立即闪退

### ISSUE THREAD

**Issue by skylarklxlong** [gucong3000/MiuiCleaner#8]
小米8SE，MIUI12.5.1，Android 10

应用启动后报错闪退
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "trim" of null (main.js.js#2)

**Comment by gucong3000** [comment]
我缺乏相同设备来复现问题，所以需要你帮助进一步调试。
由于你提供的信息未提供应用版本号，且`main.js`为压缩版本，很难定位源代码位置。现向你提供未压缩版本，希望能得到你的使用反馈：

> https://gucong.lanzoub.com/b03pbkhif
> 密码:miui

请解压`MiuiCleaner_debug.zip`文件，将其中的`MiuiCleaner_debug.apk`安装到手机运行，如果依旧报错，请提供这里的报错信息。
